version: "3"

services:
  db:
    image: mysql:5.7
    container_name: "mysql-db"
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    # networks:
    #   - default