export const translate = {
    idClient: 'Клиент',
    idEmployee: 'Работник',
    Name: 'Имя',
    Surname: 'Фамилия',
    phoneNumber: 'Номер телефона',
    ageRaiting: 'Возрастной рейтинг',
    PGraiting: 'Рейтинг по системе PG',
    minAge: 'Минимальный возвраст',
    description: 'Описание',
    idGenre: 'Жанр',
    genreFilm: 'Название жанра',
    idPlace:'Место',
    placeType:'Тип места',
    idFilm:'Фильм',
    typeFilm:'Тип фильма',
    nameFilm:'Название',
    ageRating:'Возрастной рейтинг',
    countryFilm:'Страна',
    ticketCost:'Цена за билет',
    idSession:'ID сессии',
    idTransaction:'ID транзакции',
    startTime:'Начало',
    idHall:'Зал',
    endTime:'Конец'
}